package e

const (
	//用户中心相关缓存
	CACHE_USER_CENTER_IP             = "userCenterIp"
	CACHE_USER_CENTER_IP_TIME        = 300
	CACHE_USER_CENTER_CONF           = "userCenterConfig"
	CACHE_USER_CENTER_CONF_TIME      = 300
	CACHE_USER_CENTER_CONF_FLAG      = "UserCenterConfigFlag"
	CACHE_USER_CENTER_CONF_FLAG_TIME = 300

	CACHE_ARTICLE      = "ARTICLE"
	CACHE_ARTICLE_LIST = "ARTICLE_LIST"
	CACHE_ARTICLE_TIME = 300
	CACHE_TAG          = "TAG"
	CACHE_TAG_TIME     = 300
)
